server:
  error:
    include-message: always

spring:
  application:
    name: study-reservation
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
